version: "2"

services:
  elasticsearch:
    image: andvsantana/elasticsearch:1.4.4-with-groovy
    ports:
      - 9200:9200
      - 9300:9300

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
